### ISSUE TITLE
월요일 작업 관련 (최지원)

### ISSUE THREAD

**Issue by SOSJiwon** [Sparta-A6/text-rpg-sparta-a6#2]
금일 영대님이 보내주신 것과 제 작업물 합쳐서 문제없이 돌아가도록 메인에 합칠 예정입니다!
혹시라도 추가하고 싶은 기능이 있으시면 해당 이슈로 코멘트 달아주시고 작업해주세용! (제가 그냥 궁금해서...)
간단한 거 정도는 그냥 추가해도 될 것 같기는 합니당 😆😆
아니면 쉬시는 김에 PPT에 들어갈 내용 정리 부탁드립니다! 

PPT 제작을 위한 필수 자료
1. 본인이 맡은 파트 (1개 이상) 어떤 방식으로 기능하게 만들었는지
2. 본인이 맡은 파트 또는 머지하는 과정에서 생긴 문제점, 버그 등을 어떻게 수정했는지
3. 개발과정에서 생각하게 된 점, 후기

이렇게 3개 써주시면 좋을 것 같습니다! 의견 모아서 화요일에 간단하게 PPT 만들고 대본 작성하는걸루 해요
그런김에... 발표하실분? 😁

**Comment by SOSJiwon** [comment]
@dhrzld @LeeHwangChoong  확인하시고 회신 부탁드려요!

**Comment by LeeHwangChoong** [comment]
넵 PPT 제작 자료 준비할게요 
자료 준비 하면서 추가할 거 있는지 한번 살펴볼게요
발표는 크흠;; 
말씀잘하시는 지원님이 하시면 좋을것 같습니당 ㅎㅎ

**Comment by SOSJiwon** [comment]
맞다! Read Me 도 이제 업데이트 해서 꾸며야하는데... 이것도 한번 봐주시겠어요?
일단 예쁘게는 아니어도 작업물 관련해서는 써놔야 할 것 같아서용
각 스크립트 별 담당하고 있는 기능이랑 저희 다이어그램, 플로우차트 올려놓고
구현한 기능 정도까지만 써놓으면 될 것 같습니다!
저도 머지 끝나고 붙어서 써볼게요

**Comment by LeeHwangChoong** [comment]
넵 알겠습니다
